# Generated by Django 5.0 on 2023-12-11 06:32

import django.db.models.deletion
import stationery.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stock', models.BooleanField(default=True)),
                ('display_image', models.ImageField(upload_to=stationery.utils.upload_display_image)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'stationery_items',
            },
        ),
        migrations.CreateModel(
            name='ActivePrintOuts',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('coloured_pages', models.CharField(max_length=20)),
                ('black_and_white_pages', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_message', models.TextField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=stationery.utils.printout_rename)),
                ('user', models.ForeignKey(db_column='user', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Active Print-Outs',
                'db_table': 'stationery_active_printouts',
            },
        ),
        migrations.CreateModel(
            name='ActiveOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(max_length=2)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_message', models.TextField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(db_column='item', max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationery.items')),
            ],
            options={
                'verbose_name_plural': 'Active Orders',
                'db_table': 'stationery_active_orders',
            },
        ),
        migrations.CreateModel(
            name='PastOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=7, unique=True)),
                ('quantity', models.PositiveIntegerField(max_length=2)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_message', models.TextField()),
                ('order_time', models.DateTimeField()),
                ('item', models.ForeignKey(db_column='item', max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationery.items')),
                ('user', models.ForeignKey(db_column='user', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Past Orders',
                'db_table': 'stationery_past_orders',
            },
        ),
        migrations.CreateModel(
            name='PastPrintOuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=7, unique=True)),
                ('coloured_pages', models.CharField(max_length=20)),
                ('black_and_white_pages', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_message', models.TextField()),
                ('order_time', models.DateTimeField()),
                ('file', models.FileField(upload_to=stationery.utils.printout_rename)),
                ('user', models.ForeignKey(db_column='user', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Past Print-Outs',
                'db_table': 'stationery_past_printouts',
            },
        ),
    ]
