# Generated by Django 5.0 on 2023-12-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorders',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pastorders',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
