# Generated by Django 5.0 on 2024-02-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_tempfilestorage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempFileStorage',
        ),
    ]
